[project]
name = "yamltrip"
version = "0.1.0"
description = "A round-tripping YAML library for Python"
readme = "README.md"
authors = [
    { name = "Nathan McDougall", email = "nathan.j.mcdougall@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[tool.maturin]
module-name = "yamltrip._core"
python-packages = ["yamltrip"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]
link-mode = "symlink"
default-groups = ["test", "dev"]

[tool.ty.src]
include = ["src", "tests"]

[tool.coverage]
report.exclude_also = ["if TYPE_CHECKING:", "raise AssertionError", "raise NotImplementedError", "msg = [\"']", "assert_never(.*)", "class .*\\bProtocol\\):", "@(abc\\.)?abstractmethod"]
report.omit = ["*/pytest-of-*/*"]

[tool.coverage.run]
source = ["src"]
relative_files = true

[tool.codespell]
ignore-regex = ["[A-Za-z0-9+/]{100,}"]
ignore-words-list = ["..."]
skip = ["target"]
[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "codespell>=2.4.2",
    "prek>=0.3.13",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "tomli>=2.4.1",
    "ty>=0.0.35",
]
test = [
    "coverage[toml]>=7.14.0",
]
