"""Type stubs for the yamltrip._core native module."""

from typing import Any, ClassVar, final

__all__ = [
    "Component",
    "Document",
    "Feature",
    "FeatureKind",
    "Location",
    "Op",
    "Patch",
    "Route",
    "apply_patches",
    "serialize_value",
]

@final
class Location:
    def __new__(cls, start: int, end: int) -> Location: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class FeatureKind:
    Scalar: ClassVar[FeatureKind]
    BlockMapping: ClassVar[FeatureKind]
    FlowMapping: ClassVar[FeatureKind]
    BlockSequence: ClassVar[FeatureKind]
    FlowSequence: ClassVar[FeatureKind]
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...

class Component:
    @final
    class Key(Component):
        __match_args__: ClassVar[tuple[str, ...]]
        def __new__(cls, name: str) -> Component.Key: ...
        @property
        def name(self) -> str: ...

    @final
    class Index(Component):
        __match_args__: ClassVar[tuple[str, ...]]
        def __new__(cls, index: int) -> Component.Index: ...
        @property
        def index(self) -> int: ...  # type: ignore[override]

    @staticmethod
    def key(name: str) -> Component: ...
    @staticmethod
    def index(index: int) -> Component: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Route:
    def __new__(cls, parts: list[str | int]) -> Route: ...
    def __len__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Feature:
    @property
    def location(self) -> Location: ...
    @property
    def context(self) -> Location | None: ...
    @property
    def kind(self) -> FeatureKind: ...
    @property
    def is_multiline(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Document:
    def __new__(cls, source: str) -> Document: ...
    def source(self) -> str: ...
    def query_exists(self, route: Route) -> bool: ...
    def query_exact(self, route: Route) -> Feature | None: ...
    def query_pretty(self, route: Route) -> Feature: ...
    def extract(self, feature: Feature) -> str: ...
    def parse_value(self, route: Route) -> Any: ...
    def has_anchors(self) -> bool: ...
    def apply_patches(self, patches: list[Patch]) -> Document: ...

@final
class Op:
    @staticmethod
    def replace(value: Any) -> Op: ...
    @staticmethod
    def add(key: str, value: Any) -> Op: ...
    @staticmethod
    def remove() -> Op: ...
    @staticmethod
    def append(value: Any) -> Op: ...
    @staticmethod
    def merge_into(key: str, updates: dict[str, Any]) -> Op: ...
    @staticmethod
    def insert_at(index: int, value: Any) -> Op: ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...

@final
class Patch:
    def __new__(cls, route: Route, operation: Op) -> Patch: ...
    @property
    def route(self) -> Route: ...
    @property
    def operation(self) -> Op: ...

def apply_patches(source: str, patches: list[Patch]) -> str: ...
def serialize_value(value: Any) -> str: ...
