"""Type stubs for the yamltrip._core native module."""

from typing import Any, ClassVar

class Location:
    start: int
    end: int
    def __init__(self, start: int, end: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class FeatureKind:
    Scalar: ClassVar[FeatureKind]
    BlockMapping: ClassVar[FeatureKind]
    FlowMapping: ClassVar[FeatureKind]
    BlockSequence: ClassVar[FeatureKind]
    FlowSequence: ClassVar[FeatureKind]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...

class Component:
    @staticmethod
    def key(name: str) -> Component: ...
    @staticmethod
    def index(index: int) -> Component: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Route:
    def __init__(self, parts: list[str | int]) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Feature:
    location: Location
    context: Location | None
    kind: FeatureKind
    is_multiline: bool
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Document:
    def __init__(self, source: str) -> None: ...
    def source(self) -> str: ...
    def query_exists(self, route: Route) -> bool: ...
    def query_exact(self, route: Route) -> Feature | None: ...
    def query_pretty(self, route: Route) -> Feature: ...
    def extract(self, feature: Feature) -> str: ...
    def has_anchors(self) -> bool: ...

class Op:
    @staticmethod
    def replace(value: Any) -> Op: ...
    @staticmethod
    def add(key: str, value: Any) -> Op: ...
    @staticmethod
    def remove() -> Op: ...
    @staticmethod
    def append(value: Any) -> Op: ...
    @staticmethod
    def merge_into(key: str, updates: dict[str, Any]) -> Op: ...
    def __repr__(self) -> str: ...

class Patch:
    route: Route
    operation: Op
    def __init__(self, route: Route, operation: Op) -> None: ...

def apply_patches(source: str, patches: list[Patch]) -> str: ...
def parse_value(source: str, route: Route) -> Any: ...
