name: Rust Test
permissions: {}
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - "doc/**"
      - "**/*.md"
      - ".github/workflows/static-checks.yml"
      - ".pre-commit-config.yaml"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "**/*.md"
      - ".github/workflows/static-checks.yml"
      - ".pre-commit-config.yaml"
  schedule:
    - cron: "20 14 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo-test:
    name: Cargo Test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.rust == 'beta' }}
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo test
        run: cargo test
